version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch
    volumes:
      - "./store/es:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on: ['elasticsearch']
    networks:
      - elastic

  appserver-py:
    build: ./
    container_name: appserver-py
    volumes:
      - "./src:/app"
      - "./data:/data"
    command: tail -F anything
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
